// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXnOmWvT8NMFppvb-9gZVi95dKPuV5Z4',
    appId: '1:505183064731:web:7d1dbb257516b9ababac3e',
    messagingSenderId: '505183064731',
    projectId: 'budget-tracker-a3aa9',
    authDomain: 'budget-tracker-a3aa9.firebaseapp.com',
    storageBucket: 'budget-tracker-a3aa9.firebasestorage.app',
    measurementId: 'G-ZVTXFTDV8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCF3avEYTs7b4n3lKSUntNxfrzbXwvizE',
    appId: '1:505183064731:android:fe10897129f88fcfabac3e',
    messagingSenderId: '505183064731',
    projectId: 'budget-tracker-a3aa9',
    storageBucket: 'budget-tracker-a3aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA250Fp9NSTGF5sEM1aXYGpy3zrSUrA_ok',
    appId: '1:505183064731:ios:5380a401e0ce8a85abac3e',
    messagingSenderId: '505183064731',
    projectId: 'budget-tracker-a3aa9',
    storageBucket: 'budget-tracker-a3aa9.firebasestorage.app',
    iosClientId: '505183064731-sg8qabfovkcvrfimbvtkvelpr584chvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA250Fp9NSTGF5sEM1aXYGpy3zrSUrA_ok',
    appId: '1:505183064731:ios:5380a401e0ce8a85abac3e',
    messagingSenderId: '505183064731',
    projectId: 'budget-tracker-a3aa9',
    storageBucket: 'budget-tracker-a3aa9.firebasestorage.app',
    iosClientId: '505183064731-sg8qabfovkcvrfimbvtkvelpr584chvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXnOmWvT8NMFppvb-9gZVi95dKPuV5Z4',
    appId: '1:505183064731:web:6f23b3bea613c578abac3e',
    messagingSenderId: '505183064731',
    projectId: 'budget-tracker-a3aa9',
    authDomain: 'budget-tracker-a3aa9.firebaseapp.com',
    storageBucket: 'budget-tracker-a3aa9.firebasestorage.app',
    measurementId: 'G-CDDZGTYV8X',
  );
}
