// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDreNL_AVHU7fRa-T4xyIf0T6uFfI8khio',
    appId: '1:648720292768:web:9f5224451e83f703b5a2c5',
    messagingSenderId: '648720292768',
    projectId: 'budget-app-4aa67',
    authDomain: 'budget-app-4aa67.firebaseapp.com',
    storageBucket: 'budget-app-4aa67.firebasestorage.app',
    measurementId: 'G-Q25Q471GEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBkRh8X-Lm8ntPGrvy-NDs_qnw76wM4Y',
    appId: '1:648720292768:android:bd014cc9b59ee45eb5a2c5',
    messagingSenderId: '648720292768',
    projectId: 'budget-app-4aa67',
    storageBucket: 'budget-app-4aa67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRICM94srReSDlDZIrmN5ZTXknkEiRkY',
    appId: '1:648720292768:ios:cd1810bf0fb6c1a4b5a2c5',
    messagingSenderId: '648720292768',
    projectId: 'budget-app-4aa67',
    storageBucket: 'budget-app-4aa67.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzRICM94srReSDlDZIrmN5ZTXknkEiRkY',
    appId: '1:648720292768:ios:cd1810bf0fb6c1a4b5a2c5',
    messagingSenderId: '648720292768',
    projectId: 'budget-app-4aa67',
    storageBucket: 'budget-app-4aa67.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDreNL_AVHU7fRa-T4xyIf0T6uFfI8khio',
    appId: '1:648720292768:web:5a609062770bddb6b5a2c5',
    messagingSenderId: '648720292768',
    projectId: 'budget-app-4aa67',
    authDomain: 'budget-app-4aa67.firebaseapp.com',
    storageBucket: 'budget-app-4aa67.firebasestorage.app',
    measurementId: 'G-QGXSBECS5M',
  );
}
